<a href="https://github.com/JManuelRG/cursopython/blob/main/1%20Uso%20del%20lenguaje/8.%20Vectores%20y%20Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Vectores y Matrices

## Son arreglos numéricos de datos.

### Tipos de Variables en Álgebra
Escalar: Un número único, un elemento con solo magnitud. Ej: $$1,2,3,4,3.44, \pi$$

Vectores: Son arreglos unidimensionales de números. Tienen magnitud, dirección y sentido. Ej:

$$[1,2,3,4,5,6,7,8,9,10]$$

Matrices: Son arreglos bidimensionales de números.

\begin{equation}
\begin{matrix}
1 & 2\\
3 & 4
\end{matrix}
\end{equation}


# Vectores

In [ ]:
# Vectores
# Un vector es una lista con solo números
vector = [10,20,30,40,50,60]
print(vector)

# Son indexables
for i in range(0,5):
  print(vector[i])


[10, 20, 30, 40, 50, 60]
10
20
30
40
50


In [ ]:
# Operaciones con vectores
# Sumar, Restar entre vectores
print(len(vector)) # longitud, número de elementos

vector2 = [1,2,3,4,5,6]
print(vector2)

6
[1, 2, 3, 4, 5, 6]


In [ ]:
# Operaciones 
# suma
print(f"La suma del vector {vector} + {vector2} es {vector+vector2}") # Pero es concatenación

La suma del vector [10, 20, 30, 40, 50, 60] + [1, 2, 3, 4, 5, 6] es [10, 20, 30, 40, 50, 60, 1, 2, 3, 4, 5, 6]


In [ ]:
vector+vector2 

[10, 20, 30, 40, 50, 60, 1, 2, 3, 4, 5, 6]

In [ ]:
# Si quiero la suma matemática, debe de hacerse término a término
print(vector)
print(vector2)

suma = []

for i in range(0,len(vector)-1):
  suma.append(vector[i]+vector2[i])

print(suma)

[10, 20, 30, 40, 50, 60]
[1, 2, 3, 4, 5, 6]
[11, 22, 33, 44, 55]


In [ ]:
# Si quiero la resta matemática, debe de hacerse término a término
print(vector)
print(vector2)

resta = []

for i in range(0,len(vector)-1):
  resta.append(vector[i]-vector2[i])

print(resta)

[10, 20, 30, 40, 50, 60]
[1, 2, 3, 4, 5, 6]
[9, 18, 27, 36, 45]


In [ ]:
# Para simplificar estos cálculos, existe la librería Numpy
# https://numpy.org/

# Se puede importar con el comando:
import numpy as np  
# importamos con el pseudonombre np


In [ ]:
# Declarar un vector (o array) en numpy:
arreglo = np.array([3,4,2,3,4,4,5,6])
print(arreglo)

[3 4 2 3 4 4 5 6]


In [ ]:
# Son de diferente tipo
type(vector)
type(arreglo)

numpy.ndarray

In [ ]:
arreglo2=np.array([4,2,1,2,4,6,7,9])
print(arreglo2)

[4 2 1 2 4 6 7 9]


In [ ]:
# Los arreglos se puede realizar cualquier operaci+on directamente
print(f"Arreglo: {arreglo}")
print(f"Arreglo 2: {arreglo}")
print(f"SUMA: {arreglo} + {arreglo2} = {arreglo+arreglo2}")
print(f"RESTA: {arreglo} - {arreglo2} = {arreglo-arreglo2}")

Arreglo: [3 4 2 3 4 4 5 6]
Arreglo 2: [3 4 2 3 4 4 5 6]
SUMA: [3 4 2 3 4 4 5 6] + [4 2 1 2 4 6 7 9] = [ 7  6  3  5  8 10 12 15]
RESTA: [3 4 2 3 4 4 5 6] - [4 2 1 2 4 6 7 9] = [-1  2  1  1  0 -2 -2 -3]


In [ ]:
# Herramientas:

# linspace: Permite definir un vector desde un valor inicial, hasta un valor final, con intervalos definidos
# Vector desde 1 al 100, con incrementos de 1
vector_cien = np.linspace(1,100,100) # vector que comienza en 1, finaliza en 100, con 100 elementos
print(vector_cien)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


# Matrices

# Es un arreglo bidimensional

Por ejemplo, para crear la matriz:

\begin{equation}
\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}
\end{equation}

In [ ]:
# Definir una matriz
matriz = [[1,2,3],
          [4,5,6],
          [7,8,9]]
print(matriz)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
# Acceder a los elementos de una matriz:
# Acceder a filas:
print(f"Fila 1: {matriz[0]}")
print(f"Fila 2: {matriz[1]}")
print(f"Fila 3: {matriz[2]}")

# Para acceder a columnas, de manera nativa no es posible, pero se puede implementar

Fila 1: [1, 2, 3]
Fila 2: [4, 5, 6]
Fila 3: [7, 8, 9]


\begin{equation}
\begin{matrix}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{matrix}
\end{equation}

In [ ]:
# Acceder a los elementos de la matriz, utilizamos índices (fila, columna)
# Sintaxis: Para acceder al elemento en la posición (fila, columna)
# matriz[índice de fila][índice de columna]

for fila in range(0,3):
  for columna in range(0,3):
    print(f"El elemento en la fila {fila}, columna {columna} es: {matriz[fila][columna]}")

El elemento en la fila 0, columna 0 es: 1
El elemento en la fila 0, columna 1 es: 2
El elemento en la fila 0, columna 2 es: 3
El elemento en la fila 1, columna 0 es: 4
El elemento en la fila 1, columna 1 es: 5
El elemento en la fila 1, columna 2 es: 6
El elemento en la fila 2, columna 0 es: 7
El elemento en la fila 2, columna 1 es: 8
El elemento en la fila 2, columna 2 es: 9


In [ ]:
# Definir matrices con la librería numpy
matriz1 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(matriz1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
matriz2 = np.array([[2,2,2],
                    [2,2,2],
                    [2,2,2]])
print(matriz2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
# Las matrices siguen siendo arreglos, la diferencia son sus dimensiones
print(f"El vector {arreglo} es del tipo {type(arreglo)} y es de dimensión {np.ndim(arreglo)}")
print(f"La matriz \n {matriz1} \n es del tipo {type(matriz1)} y es de dimensión {np.ndim(matriz1)}")

El vector [3 4 2 3 4 4 5 6] es del tipo <class 'numpy.ndarray'> y es de dimensión 1
La matriz 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 es del tipo <class 'numpy.ndarray'> y es de dimensión 2


In [ ]:
# Operaciones: Suma
print(matriz1)
print(matriz2)
print(matriz1+matriz2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
# Operaciones: Trigonométricas
np.sin(matriz1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [ ]:
# Acceder a los elementos de una matriz (arreglo)
print(matriz1)
matriz[0][0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [ ]:
# Métodos preestablecidos
# Sintaxis: matriz.método
print(matriz1.shape) # Devuelve las dimensiones de la matriz: fila, columna

(3, 3)


<function ndarray.max>

In [ ]:
# Inversa de una matriz
x = np.array([[1,2],[3,4]]) # Matriz original
y = np.linalg.inv(x)  # Matriz inversa
print(x) 
print(y) 
print(np.dot(x,y)) # Producto punto de las matrices 

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
